name: Build Arch Package

on:
  push:
    branches: [ "main" ]
    paths: &paths
      - '.github/workflows/arch-pkg.yml'
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches: [ "main" ]
    paths: *paths

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      env:
        CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pacman -Syu --noconfirm $(grep '\(make\)\?depends' PKGBUILD | cut -d= -f2 | sed 's/[()]//g')
      - name: Create user for makepkg
        run: useradd -m makepkg
      - name: Allow makepkg to build in current dir
        run: chown -R makepkg .
      - name: Build package
        run: su makepkg -s /bin/sh -c 'makepkg'
      - name: Install package
        run: pacman -U banger_rs-*-x86_64.pkg.tar.zst --noconfirm
