name: Arch Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      env:
        CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Build package
        run: useradd build && chown build $BUILDDIR && su build -s /bin/sh -c 'makepkg --syncdeps --noconfirm'
      - name: Install package
        run: pacman -U banger_rs-*-x86_64.pkg.tar.zst --noconfirm
